### ISSUE TITLE
2° Feedback

### ISSUE THREAD

**Issue by ElizabethVegaM** [Cloiw/cloiw.github.io#1]
Hola Claudia, revisé tu segunda entrega, me gustó mucho tu nuevo prototipo, se entiende mucho mejor lo que quieres hacer. Solo le agregaría un poco mas de color, las imágenes de tus proyectos destacan un montón pero las demás secciones están un poco plano, talvez resaltar algún elemento que consideres importante como íconos o los títulos, lo que más te haga sentido. Ahora quedaría ir desarrollandolo, cualquier cosa me dices :)

**Comment by Cloiw** [comment]
Hola, gracias! si, mientras lo iba haciendo note que los colores no iban tan bien.. siento que no los tendré bien definidos hasta tener todas las secciones completas al igual que la forma de resaltar algunos títulos

**Comment by ElizabethVegaM** [comment]
Hola! se ve muucho mejor con el efecto de cielo estrellado, creo que está bien como está ahora, solo arreglaría la sección "Acerca de mí" para que el texto quede más centrado en el div, no se si vas a usar alguna foto o vas a dejar el ícono de Git? no le veo la relación al ícono con la sección. Igual si vas a darle el mismo estilo de borde que el de los proyectos así se vería todo más cohesivo. Por lo demás está super y si quieres ir modificando o agregando más cosas recuerda que el portafolio es un proyecto "de vida" y siempre puedes ir renovándolo a tu gusto ;)

**Comment by Cloiw** [comment]
Agarre la primera img que encontré y la use como referencia jaja, pero la idea es poner una foto. 
No se me había ocurrido utilizar el mismo borde de los proyectos , definitivamente lo probare! 
gracias!!!
